- name: 'Add {{ DOMAIN }} to server path'
  ansible.builtin.lineinfile:
    path: '/mnt/data/umbrel/scripts/start'
    state: present
    regexp: '^DEVICE_HOSTS='
    line: 'DEVICE_HOSTS="http://${DEVICE_IP},http://${DEVICE_HOSTNAME}.{{ DOMAIN }},https://${DEVICE_HOSTNAME}.{{ DOMAIN }},http://${DEVICE_HOSTNAME},https://${DEVICE_HOSTNAME}"'
  notify: umbrel restart

- name: 'Add {{ DOMAIN }} to DEVICE_HOSTNAME'
  ansible.builtin.lineinfile:
    path: '/mnt/data/umbrel/scripts/start'
    state: present
    regexp: '^export DEVICE_HOSTNAME='
    line: 'export DEVICE_HOSTNAME="${DEVICE_HOSTNAME}.{{ DOMAIN }}"'
  notify: umbrel restart

- name: Add lnd color
  ansible.builtin.lineinfile:
    path: '/mnt/data/umbrel/lnd/lnd.conf'
    line: 'color={{ LND_COLOR }}'
    insertafter: '\[Application Options\]'
    state: present
  notify: umbrel restart

- name: Add lnd alias
  ansible.builtin.lineinfile:
    path: '/mnt/data/umbrel/lnd/lnd.conf'
    line: 'alias={{ LND_ALIAS }}'
    insertafter: '\[Application Options\]'
    state: present
  notify: umbrel restart
  
- name: Set time zone for server
  community.general.timezone:
    name: "{{ TZ }}"